config/routes.rb
#          new_user_password GET    /auth/secret/new(.:format)                              devise/passwords#new
#         edit_user_password GET    /auth/secret/edit(.:format)                             devise/passwords#edit
#                            PATCH  /auth/secret(.:format)                                  devise/passwords#update
#                            PUT    /auth/secret(.:format)                                  devise/passwords#update
#   cancel_user_registration GET    /auth/cancel(.:format)                                  devise/registrations#cancel
#          user_registration POST   /auth(.:format)                                         devise/registrations#create
#      new_user_registration GET    /auth/sign_up(.:format)                                 devise/registrations#new
#     edit_user_registration GET    /auth/edit(.:format)                                    devise/registrations#edit
#                            PATCH  /auth(.:format)                                         devise/registrations#update
#                            PUT    /auth(.:format)                                         devise/registrations#update
#                            DELETE /auth(.:format)                                         devise/registrations#destroy
#                auth_tokens DELETE /auth/tokens(.:format)                                  tokens#destroy {:format=>"json"}
#                            POST   /auth/tokens(.:format)                                  tokens#create {:format=>"json"}
#          auth_tokens_check GET    /auth/tokens/check(.:format)                            tokens#check {:format=>"json"}
#             link_providers GET    /link_providers(.:format)                               link_providers#index
#                            POST   /link_providers(.:format)                               link_providers#create
#          new_link_provider GET    /link_providers/new(.:format)                           link_providers#new
#         edit_link_provider GET    /link_providers/:id/edit(.:format)                      link_providers#edit
#              link_provider GET    /link_providers/:id(.:format)                           link_providers#show
#                            PATCH  /link_providers/:id(.:format)                           link_providers#update
#                            PUT    /link_providers/:id(.:format)                           link_providers#update
#                            DELETE /link_providers/:id(.:format)                           link_providers#destroy
#                    devices GET    /devices(.:format)                                      devices#index
#                            POST   /devices(.:format)                                      devices#create
#                 new_device GET    /devices/new(.:format)                                  devices#new
#                edit_device GET    /devices/:id/edit(.:format)                             devices#edit
#                     device GET    /devices/:id(.:format)                                  devices#show
#                            PATCH  /devices/:id(.:format)                                  devices#update
#                            PUT    /devices/:id(.:format)                                  devices#update
#                            DELETE /devices/:id(.:format)                                  devices#destroy
#              contact_types GET    /contact_types(.:format)                                contact_types#index
#                            POST   /contact_types(.:format)                                contact_types#create
#           new_contact_type GET    /contact_types/new(.:format)                            contact_types#new
#          edit_contact_type GET    /contact_types/:id/edit(.:format)                       contact_types#edit
#               contact_type GET    /contact_types/:id(.:format)                            contact_types#show
#                            PATCH  /contact_types/:id(.:format)                            contact_types#update
#                            PUT    /contact_types/:id(.:format)                            contact_types#update
#                            DELETE /contact_types/:id(.:format)                            contact_types#destroy
#             contact_phones GET    /contacts/:contact_id/phones(.:format)                  phones#index
#                            POST   /contacts/:contact_id/phones(.:format)                  phones#create
#          new_contact_phone GET    /contacts/:contact_id/phones/new(.:format)              phones#new
#         edit_contact_phone GET    /contacts/:contact_id/phones/:id/edit(.:format)         phones#edit
#              contact_phone GET    /contacts/:contact_id/phones/:id(.:format)              phones#show
#                            PATCH  /contacts/:contact_id/phones/:id(.:format)              phones#update
#                            PUT    /contacts/:contact_id/phones/:id(.:format)              phones#update
#                            DELETE /contacts/:contact_id/phones/:id(.:format)              phones#destroy
#             contact_photos GET    /contacts/:contact_id/photos(.:format)                  photos#index
#                            POST   /contacts/:contact_id/photos(.:format)                  photos#create
#          new_contact_photo GET    /contacts/:contact_id/photos/new(.:format)              photos#new
#         edit_contact_photo GET    /contacts/:contact_id/photos/:id/edit(.:format)         photos#edit
#              contact_photo GET    /contacts/:contact_id/photos/:id(.:format)              photos#show
#                            PATCH  /contacts/:contact_id/photos/:id(.:format)              photos#update
#                            PUT    /contacts/:contact_id/photos/:id(.:format)              photos#update
#                            DELETE /contacts/:contact_id/photos/:id(.:format)              photos#destroy
#     contact_external_links GET    /contacts/:contact_id/external_links(.:format)          external_links#index
#                            POST   /contacts/:contact_id/external_links(.:format)          external_links#create
#  new_contact_external_link GET    /contacts/:contact_id/external_links/new(.:format)      external_links#new
# edit_contact_external_link GET    /contacts/:contact_id/external_links/:id/edit(.:format) external_links#edit
#      contact_external_link GET    /contacts/:contact_id/external_links/:id(.:format)      external_links#show
#                            PATCH  /contacts/:contact_id/external_links/:id(.:format)      external_links#update
#                            PUT    /contacts/:contact_id/external_links/:id(.:format)      external_links#update
#                            DELETE /contacts/:contact_id/external_links/:id(.:format)      external_links#destroy
#                   contacts GET    /contacts(.:format)                                     contacts#index
#                            POST   /contacts(.:format)                                     contacts#create
#                new_contact GET    /contacts/new(.:format)                                 contacts#new
#               edit_contact GET    /contacts/:id/edit(.:format)                            contacts#edit
#                    contact GET    /contacts/:id(.:format)                                 contacts#show
#                            PATCH  /contacts/:id(.:format)                                 contacts#update
#                            PUT    /contacts/:id(.:format)                                 contacts#update
#                            DELETE /contacts/:id(.:format)                                 contacts#destroy
#    helpful_region_contacts GET    /regions/:region_id/contacts/helpful(.:format)          contacts#helpful
#            region_contacts GET    /regions/:region_id/contacts(.:format)                  contacts#index
#                            POST   /regions/:region_id/contacts(.:format)                  contacts#create
#         new_region_contact GET    /regions/:region_id/contacts/new(.:format)              contacts#new
#        edit_region_contact GET    /regions/:region_id/contacts/:id/edit(.:format)         contacts#edit
#             region_contact GET    /regions/:region_id/contacts/:id(.:format)              contacts#show
#                            PATCH  /regions/:region_id/contacts/:id(.:format)              contacts#update
#                            PUT    /regions/:region_id/contacts/:id(.:format)              contacts#update
#                            DELETE /regions/:region_id/contacts/:id(.:format)              contacts#destroy
#                    regions GET    /regions(.:format)                                      regions#index
#                            POST   /regions(.:format)                                      regions#create
#                 new_region GET    /regions/new(.:format)                                  regions#new
#                edit_region GET    /regions/:id/edit(.:format)                             regions#edit
#                     region GET    /regions/:id(.:format)                                  regions#show
#                            PATCH  /regions/:id(.:format)                                  regions#update
#                            PUT    /regions/:id(.:format)                                  regions#update
#                            DELETE /regions/:id(.:format)                                  regions#destroy
#                 ad_regions GET    /ads/:ad_id/regions(.:format)                           regions#index
#                            POST   /ads/:ad_id/regions(.:format)                           regions#create
#              new_ad_region GET    /ads/:ad_id/regions/new(.:format)                       regions#new
#             edit_ad_region GET    /ads/:ad_id/regions/:id/edit(.:format)                  regions#edit

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id                   :integer          not null, primary key
#  region_id            :integer
#  name                 :string(255)
#  description          :text(65535)
#  latitude             :decimal(9, 6)
#  longitude            :decimal(9, 6)
#  deleted_at           :datetime
#  created_at           :datetime
#  updated_at           :datetime
#  contact_type_id      :integer
#  sponsorship_id       :integer
#  address              :text(65535)
#  helpful              :boolean          default(FALSE)
#  sync_uuid            :string(255)
#  open_24              :boolean          default(FALSE)
#  search_field         :text(65535)
#  address_for_geocoder :text(65535)
#  on_call_drugstore    :boolean          default(FALSE)
#

require 'csv'

class Contact < ActiveRecord::Base
  scope :global_filter, -> (name) { where("contacts.name like ? or contacts.description like ? or contacts.search_field like ?", "%#{name}%", "%#{name}%", "%#{name}%")}
  scope :region_filter, -> (region_id) { where region_id: region_id }
  scope :contact_type_filter, -> (contact_type_id) { joins(:contact_types).where contact_types_contacts: {contact_type_id: contact_type_id} }


  acts_as_paranoid

  belongs_to :region
  # belongs_to :contact_type

  has_and_belongs_to_many :photos, after_add: :resource_added, after_remove: [Proc.new { |p, d| p.updated_at = Time.now}]
  has_and_belongs_to_many :external_links, after_add: :resource_added, before_remove: [:resource_added, Proc.new { |p, d| p.updated_at = Time.now}]
  has_and_belongs_to_many :contact_types

  has_many :phones
  has_many :ads

  accepts_nested_attributes_for :photos, allow_destroy: true
  accepts_nested_attributes_for :phones, allow_destroy: true
  accepts_nested_attributes_for :external_links, allow_destroy: true, reject_if: proc { |attributes| attributes['link'].blank? }

  include Syncable

  validates :name, presence: true
  validates :region, presence: true
  # validates :contact_type, presence: true

  validates_presence_of :phones

  after_save :calculate_geoposition

  def resource_added(photo)
    if self.persisted?
      self.touch
      puts "Adicionado".red
    end
  end

  private
  def calculate_geoposition
    if self.address_for_geocoder_changed? || region_id_changed?
      self.delay.invoke_geocoder(self)
    end
  end

  def invoke_geocoder(contact)
    full_address = ""
    if (contact.address_for_geocoder.present?)
      full_address = self.address_for_geocoder
    end

    geocoded = Geocoder.search(full_address)

    if (geocoded.present?)
      most_accurate = geocoded.first
      contact.latitude = most_accurate.latitude
      contact.longitude = most_accurate.longitude
    else
      contact.latitude = nil
      contact.longitude = nil
    end

    contact.save
  end

  def self.import(file, region)
    file_text = file.read
    file_text = file_text.force_encoding("utf-8")
    errors = parse_spreadsheet(file_text, region)
  end

  def self.parse_spreadsheet(file_text, region)
    n = 0
    header = nil
    errors = []
    contacts = []

    CSV.parse(file_text) do |row|
      n += 1
      if (n == 1)
        header = row
        next
      end
      if (row.join.blank?)
        next
      end

      transposed_row = Hash[[header, row].transpose]

      contact = Contact.build_from_csv(transposed_row)
      contact.region = region

      if contact.valid?
        contacts.push(contact)
      else
        errors << row
      end

      if (n % 1000 == 0)
        Contact.perform_transaction(contacts)
        contacts = []
      end

    end

    Contact.perform_transaction(contacts)

    return errors
  end

  def self.perform_transaction(contacts)
    Contact.transaction do
      contacts.each(&:save!)
    end
  end

  def self.build_from_csv(csv)
    contact = Contact.new
    contact.name = csv["nome"]
    contact.address = csv["endereco"]

    phone1 = csv["telefone1"]
    phone2 = csv["telefone2"]
    phone3 = csv["telefone3"]
    phone4 = csv["telefone4"]

    carrier1 = csv["operadora1"]
    carrier2 = csv["operadora2"]
    carrier3 = csv["operadora3"]
    carrier4 = csv["operadora4"]

    phone = nil

    if (phone1.present?)
      phone = Phone.new
      phone.number = phone1.gsub(/\D/, '').to_i
      phone.carrier = carrier1
      contact.phones << phone
    end

    if (phone2.present?)
      phone = Phone.new
      phone.number = phone2.gsub(/\D/, '').to_i
      phone.carrier = carrier2
      contact.phones << phone
    end

    if (phone3.present?)
      phone = Phone.new
      phone.number = phone3.gsub(/\D/, '').to_i
      phone.carrier = carrier3
      contact.phones << phone
    end

    if (phone4.present?)
      phone = Phone.new
      phone.number = phone4.gsub(/\D/, '').to_i
      phone.carrier = carrier4
      contact.phones << phone
    end
    return contact
  end
end

app/models/contact_type.rb
# == Schema Information
#
# Table name: contact_types
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  deleted_at             :datetime
#  created_at             :datetime
#  updated_at             :datetime
#  parent_contact_type_id :integer
#

class ContactType < ActiveRecord::Base
  acts_as_paranoid

  # has_many :contacts, dependent: :restrict_with_error

  scope :only_parents, -> { where('ifnull(parent_contact_type_id,0) = 0') }
  scope :without_parents, -> { where('ifnull(parent_contact_type_id,0) <> 0') }

  belongs_to :parent, class_name: 'ContactType', foreign_key: :parent_contact_type_id

  has_and_belongs_to_many :contacts
  has_attached_file :uploader, :styles => { :medium => "300x300#", :thumb => "100x100#" }

  validates :name, presence: true
  validates :parent, presence: true
  validates_attachment_content_type :uploader, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/views/contacts/_additional_info.html.erb
<h3><%= t('general.additional_info') %></h3>
<ul class="nav nav-list">
  <% if @resource.instance_of?(Contact) %>
    <li><%= link_to "<i class='icon icon-material-phone pull-right'></i> #{Phone.model_name.human(count: 2)}".html_safe, url_for([@resource, :phones])  %></li>
    <li><%= link_to "<i class='icon icon-material-photo pull-right'></i> #{Photo.model_name.human(count: 2)}".html_safe, url_for([@resource, :photos])  %></li>
    <li><%= link_to "<i class='icon icon-material-link pull-right'></i> #{ExternalLink.model_name.human(count: 2)}".html_safe, url_for([@resource, :external_links])  %></li>
  <% elsif @resource.instance_of?(Ad) %>
    <li><%= link_to "<i class='icon icon-material-photo pull-right'></i> #{Photo.model_name.human(count: 2)}".html_safe, url_for([@resource, :photos])  %></li>
    <li><%= link_to "<i class='icon icon-material-link pull-right'></i> #{ExternalLink.model_name.human(count: 2)}".html_safe, url_for([@resource, :external_links])  %></li>
  <% end %>
  <% if @region.present? %>
      <%= render :partial => "regions/sidebar" %>
  <% end %>
</ul>

app/views/contacts/_form.html.erb
<% if @contact.errors.any? %>
  <div id="error_expl" class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h3>
    </div>
    <div class="panel-body">
      <ul>
        <% @contact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<%= form_for [@region, @contact], :html => { :multipart => true, :class => "form-horizontal contact" } do |f| %>



  <div class="form-group">
    <%= f.label :name, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :search_field, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-10">
      <%= f.text_field :search_field, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :contact_type_ids, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-10">
      <%= f.collection_select :contact_type_ids, ContactType.without_parents.order(:name), :id, :name, {include_blank: 'Selecione o tipo de contato'}, {:class => 'form-control selectize', multiple: true} %>
    </div>
  </div>

  <% if @region.blank? %>
    <div class="form-group">
      <%= f.label :region_id, :class => 'col-lg-2 col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= f.collection_select :region_id, Region.all, :id, :name, {}, {:class => 'form-control'} %>
      </div>
    </div>
  <% else %>
    <%= f.hidden_field :helpful %>
  <% end %>

  <div class="form-group">
    <%= f.label :address, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-10">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :address_for_geocoder, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-10">
      <%= f.text_field :address_for_geocoder, :class => 'form-control' %>
    </div>
  </div>


  <br />
  <%= f.fields_for :phones do |phones_form| %>
    <div class="form-group">
      <%= phones_form.label "Telefone principal", :class => 'col-lg-2 control-label' %>
      <div class="col-lg-2">
        <%= phones_form.phone_field :area, class: 'form-control' %>
        <span class="help-block">Código de área</span>
      </div>
      <div class="col-lg-2">
        <%= phones_form.phone_field :number, class: 'form-control' %>
        <span class="help-block">Número</span>
      </div>
      <div class="col-lg-2">
        <%= phones_form.select :carrier, options_for_select(Phone.carrier_attributes_for_select, selected: phones_form.object.try(:carrier)), {:include_blank => 'Selecione a operadora'} , class: "form-control" %>
        <span class="help-block">Operadora</span>
      </div>
    </div>
  <% end %>

  <br />
  <%= f.fields_for :external_links do |external_link| %>
    <div class="form-group">
      <%= external_link.label "Link principal", :class => 'col-lg-2 control-label' %>
      <div class="col-lg-3">
        <%= external_link.select :link_type, options_for_select(ExternalLink.link_type_attributes_for_select, selected: external_link.object.try(:link_type)), {} , class: "form-control" %>
        <span class="help-block">Tipo</span>
      </div>

      <div class="col-lg-3">
        <%= external_link.text_field :link, :class => 'form-control' %>
        <span class="help-block">Link de acesso</span>
      </div>
      <div class="col-lg-3">
        <%= external_link.text_field :name, :class => 'form-control' %>
        <span class="help-block">Nome do link</span>
      </div>
    </div>
  <% end %>

    <div class="form-group">
      <%= f.label :open_24, :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= f.check_box :open_24, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :on_call_drugstore, :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= f.check_box :on_call_drugstore, :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :subscriber, :class => 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= f.check_box :subscriber, :class => 'form-control' %>
      </div>
    </div>
  <% if @contact.photos.main_photos.empty? %>
      <%= f.fields_for :photos, @contact.photos.build do |photo_builder| %>
          <div class="form-group">
            <%= photo_builder.label t('general.contact_photo'), :class => 'col-lg-2 control-label' %>
            <div class="col-lg-10">
              <input type="text" readonly="" class="form-control floating-label" placeholder="<%= t('general.contact_photo_placeholder') %>">
              <%= photo_builder.file_field :file %>
              <%= photo_builder.hidden_field :main, :value => true %>
            </div>
          </div>
      <% end %>
  <% else %>
        <!-- MAIN PHOTOS -->
        <div class="row">
          <% @contact.photos.main_photos.each do |photo_builder| %>
            <div class="col-sm-6 col-md-4" >
              <div class="thumbnail">
                <img src="<%= photo_builder.file.url(:original) %>" alt="...">
                <h2 class="label center-block"><%= t("general.main_photo") %></h2>
                <% if (photo_builder.persisted?) %>
                    <%= link_to '<i class="icon mdi-content-remove-circle"></i>'.html_safe,
                                url_for([@contact, photo_builder]),
                                :method => :delete,
                                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                                :class => 'btn btn-icon btn-danger btn-delete-img' %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
  <% end %>

    <!-- NORMAL PHOTOS -->
    <div class="row">
      <% @contact.photos.normal_photos.each do |photo_builder| %>
          <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
              <img src="<%= photo_builder.file.url(:original) %>" alt="...">
              <% if (photo_builder.persisted?) %>
                  <%= link_to '<i class="icon mdi-content-remove-circle"></i>'.html_safe,
                              url_for([@contact, photo_builder]),
                              :method => :delete,
                              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                              :class => 'btn btn-icon btn-danger btn-delete-img' %>
              <% end %>
            </div>
          </div>
      <% end %>
    </div>



  <% if @helpful_contacts %>
    <div class="actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  helpful_region_contacts_path(@region), :class => 'btn btn-default' %>
    </div>
  <% else %>
    <div class="actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  url_for([@region, :contacts]), :class => 'btn btn-default' %>
    </div>
  <% end %>

<% end %>

app/views/contacts/_sidebar.html.erb
<% content_for :sidebar do %>
    <%- model_class = Contact -%>
    <h3><%= t('general.contact_info') %></h3>
    <dl class="dl-vertical">
      <dt><strong><%= model_class.human_attribute_name(:region_id) %>:</strong></dt>
      <dd><%= @resource.region.name %></dd>
      <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
      <dd><%= @resource.name %></dd>
      <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
      <dd><%= @resource.description %></dd>
      <% if (@resource.contact_types.present?) %>
        <dt><strong><%= model_class.human_attribute_name(:contact_types) %>:</strong></dt>
        <dd><%= @resource.contact_types.map(&:name).join(', ') %></dd>
      <% end %>
    </dl>
    <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_contact_path(@resource), :class => 'btn btn-xs btn-primary' %>

    <%= render :partial => 'contacts/additional_info' %>

<% end %>

app/views/contacts/edit.html.erb
<div class="well">
  <%= render :partial => 'form' %>
</div>

<% content_for :sidebar do %>
    <%= render :partial => 'additional_info' %>
<% end %>

app/views/contacts/import_csv.html.erb
<h2>Importar Contatos</h2>

<%= form_tag import_region_contacts_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/contacts/index.html.erb
<div class="well">
  <%- model_class = Contact -%>
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human(:count => 2).titleize %></h1>
    <%= link_to t('.new', :default => t("helpers.links.new")),
                url_for([:new, @region, :contact, params: {helpful: @helpful_contacts}]),
                :class => 'btn btn-primary' %>
  </div>

  <%= form_tag '', :method => :get, class: "form-inline", role: "form" do %>
    <div class="form-group">
        <%= text_field_tag :global_filter, @global_filter, class: "form-control", placeholder: "Busca..." %>
    </div>

    <% if !@region.present? || !@region.instance_of?(Region) %>
      <div class="form-group">
        <%= select_tag :region_filter, options_from_collection_for_select(Region.all.order('name asc'), "id", "name", @region_filter), prompt: "Selecione a região", class: "form-control" %>
      </div>
    <% end %>

    <div class="form-group">
      <%= select_tag :contact_type_filter, options_from_collection_for_select(ContactType.all.order('name asc'), "id", "name", @contact_type_filter), prompt: "Selecione a categoria", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= submit_tag 'Filtrar', class: "btn btn-default btn-sm" %>
    </div>
  <% end %>

  <table class="table table-striped">
    <thead>
    <tr>
      <th width="30%"><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:contact_types) %></th>
      <th><%= model_class.human_attribute_name(:region) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
    </thead>
    <tbody>
    <% @contacts.each do |contact| %>
        <tr>
          <% unless contact.latitude.present? || contact.longitude.present?%>
              <td><%= contact.name %> <i> (<%= t('general.address_not_found')%>) </i></td>
          <% else %>
              <td><%= contact.name %></td>
          <% end %>

          <% if contact.contact_types.present? %>
            <td><%= contact.contact_types.order(:name).map(&:name).join(', ') %></td>
          <% else %>
          <td></td>
          <% end %>
          <td><%= contact.region.name %></td>
          <td>
            <%= link_to '<i class="icon mdi-content-create"></i>'.html_safe,
                        url_for([:edit, @region, contact]), :class => 'btn btn-default btn-icon btn-small' %>
            <%= link_to '<i class="icon mdi-content-remove-circle"></i>'.html_safe,
                        url_for([@region, contact]),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-icon btn-default  btn-small' %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <%= will_paginate @contacts, renderer: BootstrapPagination::Rails %>
  <br />

  <div class="pull-right">
    <% if (@region.present?) %>
        <%= link_to t('.import', :default => t("helpers.links.import")),
                    import_csv_region_contacts_path(@region),
                    :class => 'btn btn-primary' %>
    <% end %>

    <%= link_to t('.new', :default => t("helpers.links.new")),
                url_for([:new, @region, :contact, params: {helpful: @helpful_contacts}]),
                :class => 'btn btn-primary' %>
  </div>
    <div class="clearfix"></div>

</div>

<% content_for :sidebar do %>
  <%- if @region.class.name == 'Region' -%>
    <%= render 'regions/sidebar' %>
  <%- end -%>
<% end %>

app/views/contacts/new.html.erb
<div class="well">
  <%= render :partial => 'form' %>
</div>

<% content_for :sidebar do %>
  <%- if @region.class.name == 'Region' -%>
    <%= render 'regions/sidebar' %>
  <%- end -%>
<% end %>

app/views/contacts/show.html.erb
<%- model_class = Contact -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:region_id) %>:</strong></dt>
  <dd><%= @contact.region_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @contact.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @contact.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:latitude) %>:</strong></dt>
  <dd><%= @contact.latitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:longitude) %>:</strong></dt>
  <dd><%= @contact.longitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:deleted_at) %>:</strong></dt>
  <dd><%= @contact.deleted_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact_type_id) %>:</strong></dt>
  <dd><%= @contact.contact_type_id %></dd>

  <div class="row">
  <% @contact.photos.each_with_index  do |photo, index| %>
      <div class="col-sm-2 col-md-1 ">
        <div class="thumbnail">
          <img src="<%= photo.file.url(:thumb) %>" alt=""/>
        </div>
      </div>
  <%  end %>

  </div>

</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              contacts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_contact_path(@contact), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              contact_path(@contact),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>